# Generated by Django 5.0.6 on 2024-08-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='full_name',
        ),
        migrations.AddField(
            model_name='users',
            name='firstname',
            field=models.CharField(default='John', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='lastname',
            field=models.CharField(default='Doe', max_length=20),
        ),
    ]
