# Generated by Django 5.0.6 on 2024-08-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_users_full_name_users_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Date_Of_Birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
