# Generated by Django 5.0.6 on 2024-07-22 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_users_email_users_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name_plural': 'Reviews'},
        ),
    ]
