# Generated by Django 5.0.6 on 2024-08-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_users_date_of_birth_users_age_users_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone_number',
            field=models.IntegerField(null='true'),
            preserve_default='true',
        ),
    ]
