# Generated by Django 5.0.6 on 2024-08-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_users_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Date_Of_Birth',
            new_name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='users',
            name='age',
        ),
        migrations.AlterField(
            model_name='users',
            name='firstname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='lastname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
