# Generated by Django 5.0.6 on 2024-08-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_date_of_birth_users_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='content_images',
            field=models.FileField(null=True, upload_to='Articles/content_images/'),
        ),
        migrations.AddField(
            model_name='articles',
            name='cover_image',
            field=models.FileField(null=True, upload_to='Articles/cover_images/'),
        ),
        migrations.AddField(
            model_name='articles',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articles',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
