# Generated by Django 5.0.6 on 2024-08-21 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_articleviews_remove_articles_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleviews',
            old_name='auhtor',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='articleviews',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.articles'),
        ),
    ]
