# Generated by Django 5.0.6 on 2024-08-21 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_auhtor_articleviews_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislikes',
            old_name='article',
            new_name='article_id',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='article',
        ),
        migrations.AddField(
            model_name='likes',
            name='article_id',
            field=models.ForeignKey(default='22', on_delete=django.db.models.deletion.CASCADE, to='main.articles'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='likes',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
