# Generated by Django 5.0.6 on 2024-08-24 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_articles_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecomments',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='articledislikes',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='articlelikes',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='articlesaves',
            old_name='article_id',
            new_name='article',
        ),
        migrations.AlterField(
            model_name='articlelikes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articleviews',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitereviews',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
