# Generated by Django 5.0.6 on 2024-08-24 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_article_id_articlecomments_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledislikes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
