# Generated by Django 5.0.6 on 2024-09-01 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_articledislikes_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesaves',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
